
import { Driver } from '../../types/types';
import { mockTransportCompanies } from './mock-transport-companies';

export const mockDrivers: Driver[] = [
  {
    id: 1,
    name: "Juan dela Cruz",
    license_number: "N01-23-456789",
    transport_company: mockTransportCompanies[0],
    nfc_code: "NFC001",
    status: "in_terminal",
    last_nfc_tap_time: "2024-01-15T08:00:00Z",
    profile_picture: "/drivers/driver1.jpg",
    applicant: "Juan dela Cruz",
    citizenship: "Filipino",
    address: "123 Main St, Cagayan de Oro City",
    name_of_vehicle: "Hyundai Universe",
    destination: "Iligan City",
    type_of_vehicle: "Bus",
    seating_capacity: 45,
    franchise_number: "FRA-2023-001",
    plate_number: "ABC 1234",
    conductor_name: "Pedro Santos"
  },
  {
    id: 2,
    name: "Maria Clara",
    license_number: "N02-34-567890",
    transport_company: mockTransportCompanies[1],
    nfc_code: "NFC002",
    status: "departed",
    last_nfc_tap_time: "2024-01-16T09:00:00Z",
    profile_picture: "/drivers/driver2.jpg",
    applicant: "Maria Clara",
    citizenship: "Filipino",
    address: "456 Secondary St, Iligan City",
    name_of_vehicle: "Toyota HiAce",
    destination: "Cagayan de Oro City",
    type_of_vehicle: "Van",
    seating_capacity: 14,
    franchise_number: "FRA-2023-002",
    plate_number: "XYZ 5678",
    conductor_name: "Jose Rizal"
  },
  {
    id: 3,
    name: "Jose Rizal",
    license_number: "N03-45-678901",
    transport_company: mockTransportCompanies[2],
    nfc_code: "NFC003",
    status: "arrived",
    last_nfc_tap_time: "2024-01-17T10:00:00Z",
    profile_picture: "/drivers/driver3.jpg",
    applicant: "Jose Rizal",
    citizenship: "Filipino",
    address: "789 Tertiary St, Butuan City",
    name_of_vehicle: "Golden Dragon",
    destination: "Davao City",
    type_of_vehicle: "Bus",
    seating_capacity: 50,
    franchise_number: "FRA-2023-003",
    plate_number: "DEF 9012",
    conductor_name: "Andres Bonifacio"
  },
  {
    id: 4,
    name: "Andres Bonifacio",
    license_number: "N04-56-789012",
    transport_company: mockTransportCompanies[0],
    nfc_code: "NFC004",
    status: "in_terminal",
    last_nfc_tap_time: "2024-01-18T11:00:00Z",
    profile_picture: "/drivers/driver4.jpg",
    applicant: "Andres Bonifacio",
    citizenship: "Filipino",
    address: "101 Quaternary St, Davao City",
    name_of_vehicle: "Nissan Urvan",
    destination: "Butuan City",
    type_of_vehicle: "Van",
    seating_capacity: 14,
    franchise_number: "FRA-2023-004",
    plate_number: "GHI 3456",
    conductor_name: "Emilio Aguinaldo"
  },
  {
    id: 5,
    name: "Emilio Aguinaldo",
    license_number: "N05-67-890123",
    transport_company: mockTransportCompanies[1],
    nfc_code: "NFC005",
    status: "departed",
    last_nfc_tap_time: "2024-01-19T12:00:00Z",
    profile_picture: "/drivers/driver5.jpg",
    applicant: "Emilio Aguinaldo",
    citizenship: "Filipino",
    address: "202 Quinary St, General Santos City",
    name_of_vehicle: "Yutong ZK6127H",
    destination: "Surigao City",
    type_of_vehicle: "Bus",
    seating_capacity: 48,
    franchise_number: "FRA-2023-005",
    plate_number: "JKL 7890",
    conductor_name: "Apolinario Mabini"
  },
  {
    id: 6,
    name: "Apolinario Mabini",
    license_number: "N06-78-901234",
    transport_company: mockTransportCompanies[2],
    nfc_code: "NFC006",
    status: "arrived",
    last_nfc_tap_time: "2024-01-20T13:00:00Z",
    profile_picture: "/drivers/driver6.jpg",
    applicant: "Apolinario Mabini",
    citizenship: "Filipino",
    address: "303 Senary St, Surigao City",
    name_of_vehicle: "Mercedes-Benz Sprinter",
    destination: "Valencia City",
    type_of_vehicle: "Van",
    seating_capacity: 16,
    franchise_number: "FRA-2023-006",
    plate_number: "MNO 1234",
    conductor_name: "Melchora Aquino"
  },
  {
    id: 7,
    name: "Melchora Aquino",
    license_number: "N07-89-012345",
    transport_company: mockTransportCompanies[0],
    nfc_code: "NFC007",
    status: "in_terminal",
    last_nfc_tap_time: "2024-01-21T14:00:00Z",
    profile_picture: "/drivers/driver7.jpg",
    applicant: "Melchora Aquino",
    citizenship: "Filipino",
    address: "404 Septenary St, Valencia City",
    name_of_vehicle: "Volvo 9800",
    destination: "Malaybalay City",
    type_of_vehicle: "Bus",
    seating_capacity: 52,
    franchise_number: "FRA-2023-007",
    plate_number: "PQR 5678",
    conductor_name: "Marcelo del Pilar"
  },
  {
    id: 8,
    name: "Marcelo del Pilar",
    license_number: "N08-90-123456",
    transport_company: mockTransportCompanies[1],
    nfc_code: "NFC008",
    status: "departed",
    last_nfc_tap_time: "2024-01-22T15:00:00Z",
    profile_picture: "/drivers/driver8.jpg",
    applicant: "Marcelo del Pilar",
    citizenship: "Filipino",
    address: "505 Octonary St, Malaybalay City",
    name_of_vehicle: "Ford Transit",
    destination: "Ozamiz City",
    type_of_vehicle: "Van",
    seating_capacity: 15,
    franchise_number: "FRA-2023-008",
    plate_number: "STU 9012",
    conductor_name: "Antonio Luna"
  },
  {
    id: 9,
    name: "Antonio Luna",
    license_number: "N09-01-234567",
    transport_company: mockTransportCompanies[2],
    nfc_code: "NFC009",
    status: "arrived",
    last_nfc_tap_time: "2024-01-23T16:00:00Z",
    profile_picture: "/drivers/driver9.jpg",
    applicant: "Antonio Luna",
    citizenship: "Filipino",
    address: "606 Nonary St, Ozamiz City",
    name_of_vehicle: "Scania Touring",
    destination: "Pagadian City",
    type_of_vehicle: "Bus",
    seating_capacity: 49,
    franchise_number: "FRA-2023-009",
    plate_number: "VWX 3456",
    conductor_name: "Gregorio del Pilar"
  },
  {
    id: 10,
    name: "Gregorio del Pilar",
    license_number: "N10-12-345678",
    transport_company: mockTransportCompanies[0],
    nfc_code: "NFC010",
    status: "in_terminal",
    last_nfc_tap_time: "2024-01-24T17:00:00Z",
    profile_picture: "/drivers/driver10.jpg",
    applicant: "Gregorio del Pilar",
    citizenship: "Filipino",
    address: "707 Denary St, Pagadian City",
    name_of_vehicle: "Maxus V80",
    destination: "Cagayan de Oro City",
    type_of_vehicle: "Van",
    seating_capacity: 13,
    franchise_number: "FRA-2023-010",
    plate_number: "YZA 7890",
    conductor_name: "Diego Silang"
  }
];