// itmsv3/src/lib/mockfolder/mock-vehicles.ts

import { Vehicle } from '../../types/types';
import { mockTransportCompanies } from './mock-transport-companies';

export const mockVehicles: Vehicle[] = [
  {
    id: 1,
    vehicle_type: "Bus",
    model_name: "Hyundai Universe",
    year: 2023,
    plate_number: "ABC 1234",
    color: "White",
    capacity: 45,
    available: true,
    qr_code: "/qr/vehicle-1.png",
    transport_company: mockTransportCompanies[0],
    ltt_number: "LTT-2023-001",
    lto_number: "LTO-2023-001",
    franchise_number: "FRA-2023-001",
    status: "operational",
    violation_count: 0,
    picture: "/vehicles/bus-1.jpg"
  },
  {
    id: 2,
    vehicle_type: "Van",
    model_name: "Toyota HiAce",
    year: 2022,
    plate_number: "XYZ 5678",
    color: "Silver",
    capacity: 14,
    available: true,
    qr_code: "/qr/vehicle-2.png",
    transport_company: mockTransportCompanies[1],
    ltt_number: "LTT-2023-002",
    lto_number: "LTO-2023-002",
    franchise_number: "FRA-2023-002",
    status: "operational",
    violation_count: 1,
    picture: "/vehicles/van-1.jpg"
  },
  {
    id: 3,
    vehicle_type: "Bus",
    model_name: "Golden Dragon",
    year: 2023,
    plate_number: "DEF 9012",
    color: "Blue",
    capacity: 50,
    available: true,
    qr_code: "/qr/vehicle-3.png",
    transport_company: mockTransportCompanies[2],
    ltt_number: "LTT-2023-003",
    lto_number: "LTO-2023-003",
    franchise_number: "FRA-2023-003",
    status: "operational",
    violation_count: 0,
    picture: "/vehicles/bus-2.jpg"
  },
  {
    id: 4,
    vehicle_type: "Van",
    model_name: "Nissan Urvan",
    year: 2022,
    plate_number: "GHI 3456",
    color: "White",
    capacity: 14,
    available: false,
    qr_code: "/qr/vehicle-4.png",
    transport_company: mockTransportCompanies[0],
    ltt_number: "LTT-2023-004",
    lto_number: "LTO-2023-004",
    franchise_number: "FRA-2023-004",
    status: "maintenance",
    violation_count: 2,
    picture: "/vehicles/van-2.jpg"
  },
  {
    id: 5,
    vehicle_type: "Bus",
    model_name: "Yutong ZK6127H",
    year: 2023,
    plate_number: "JKL 7890",
    color: "Red",
    capacity: 48,
    available: true,
    qr_code: "/qr/vehicle-5.png",
    transport_company: mockTransportCompanies[1],
    ltt_number: "LTT-2023-005",
    lto_number: "LTO-2023-005",
    franchise_number: "FRA-2023-005",
    status: "operational",
    violation_count: 0,
    picture: "/vehicles/bus-3.jpg"
  },
  {
    id: 6,
    vehicle_type: "Van",
    model_name: "Mercedes-Benz Sprinter",
    year: 2022,
    plate_number: "MNO 1234",
    color: "Black",
    capacity: 16,
    available: true,
    qr_code: "/qr/vehicle-6.png",
    transport_company: mockTransportCompanies[2],
    ltt_number: "LTT-2023-006",
    lto_number: "LTO-2023-006",
    franchise_number: "FRA-2023-006",
    status: "operational",
    violation_count: 1,
    picture: "/vehicles/van-3.jpg"
  },
  {
    id: 7,
    vehicle_type: "Bus",
    model_name: "Volvo 9800",
    year: 2023,
    plate_number: "PQR 5678",
    color: "Silver",
    capacity: 52,
    available: true,
    qr_code: "/qr/vehicle-7.png",
    transport_company: mockTransportCompanies[0],
    ltt_number: "LTT-2023-007",
    lto_number: "LTO-2023-007",
    franchise_number: "FRA-2023-007",
    status: "operational",
    violation_count: 0,
    picture: "/vehicles/bus-4.jpg"
  },
  {
    id: 8,
    vehicle_type: "Van",
    model_name: "Ford Transit",
    year: 2022,
    plate_number: "STU 9012",
    color: "White",
    capacity: 15,
    available: false,
    qr_code: "/qr/vehicle-8.png",
    transport_company: mockTransportCompanies[1],
    ltt_number: "LTT-2023-008",
    lto_number: "LTO-2023-008",
    franchise_number: "FRA-2023-008",
    status: "parked",
    violation_count: 3,
    picture: "/vehicles/van-4.jpg"
  },
  {
    id: 9,
    vehicle_type: "Bus",
    model_name: "Scania Touring",
    year: 2023,
    plate_number: "VWX 3456",
    color: "Green",
    capacity: 49,
    available: true,
    qr_code: "/qr/vehicle-9.png",
    transport_company: mockTransportCompanies[2],
    ltt_number: "LTT-2023-009",
    lto_number: "LTO-2023-009",
    franchise_number: "FRA-2023-009",
    status: "operational",
    violation_count: 0,
    picture: "/vehicles/bus-5.jpg"
  },
  {
    id: 10,
    vehicle_type: "Van",
    model_name: "Maxus V80",
    year: 2022,
    plate_number: "YZA 7890",
    color: "Silver",
    capacity: 13,
    available: true,
    qr_code: "/qr/vehicle-10.png",
    transport_company: mockTransportCompanies[0],
    ltt_number: "LTT-2023-010",
    lto_number: "LTO-2023-010",
    franchise_number: "FRA-2023-010",
    status: "operational",
    violation_count: 1,
    picture: "/vehicles/van-5.jpg"
  }
];